# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.6
language: objective-c
xcode_workspace: HJLayout.xcworkspace
xcode_scheme: HJLayout-Example
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro
before_script: cd Example #specifying build folder
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
